[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[dependencies]
mpd = "0.1.0"
anyhow = "1.0.100"
discord-rich-presence = "1.0.0"
reqwest = { version = "0.12.23", features = ["blocking", "multipart"] }
tempfile = "3.23.0"